// Code generation service
// Generates JS/MD files for the frontend from database content.
// Called by GitHub Actions during the deploy workflow.

import { createClient } from '@supabase/supabase-js';

interface CodegenOptions {
  supabaseUrl: string;
  supabaseKey: string;
  outputDir: string; // Path to Puxijietech/apps/web/src/
}

export async function generateAllProducts(opts: CodegenOptions): Promise<string> {
  const supabase = createClient(opts.supabaseUrl, opts.supabaseKey);
  const { data: products } = await supabase
    .from('products')
    .select(`*, product_translations(*), product_specs(*), product_images(media_id, sort_order, is_primary, media(*))`)
    .eq('is_published', true)
    .order('sort_order');

  if (!products) return '';

  const lines: string[] = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    '// Generated at: ' + new Date().toISOString(),
    '',
  ];

  // Generate image imports
  const imageImports: string[] = [];
  for (const p of products) {
    for (const img of p.product_images || []) {
      const media = img.media;
      if (media?.variants?.publicUrl) {
        const varName = `${p.slug.replace(/-/g, '_')}_img_${img.sort_order}`;
        lines.push(`import ${varName} from '${media.variants.publicUrl}?w=240;360;480;560;640;720;1080;1600&format=webp&quality=76&as=img';`);
        imageImports.push(varName);
      }
    }
  }

  lines.push('');
  lines.push('const rawProducts = [');

  for (const p of products) {
    const en = p.product_translations?.find((t: any) => t.locale === 'en');
    const fr = p.product_translations?.find((t: any) => t.locale === 'fr');
    const vi = p.product_translations?.find((t: any) => t.locale === 'vi');
    const specs = p.product_specs || {};

    // Collect image references
    const productImages = (p.product_images || []).sort((a: any, b: any) => a.sort_order - b.sort_order);
    const imageRefs = productImages.map((_: any, i: number) => `${p.slug.replace(/-/g, '_')}_img_${i}`);

    lines.push(`  {`);
    lines.push(`    id: '${p.slug}',`);
    lines.push(`    name: '${(en?.name || '').replace(/'/g, "\\'")}',`);
    lines.push(`    category: '${p.category}',`);
    lines.push(`    image: [${imageRefs.join(', ')}],`);

    // Translations
    lines.push(`    translations: {`);
    for (const loc of ['en', 'fr', 'vi']) {
      const t = [en, fr, vi].find((x) => x?.locale === loc);
      if (t) {
        lines.push(`      ${loc}: {`);
        lines.push(`        name: '${(t.name || '').replace(/'/g, "\\'")}',`);
        lines.push(`        material: '${(t.material || '').replace(/'/g, "\\'")}',`);
        lines.push(`        features: ${JSON.stringify(t.features || [])},`);
        lines.push(`        benefits: ${JSON.stringify(t.benefits || [])},`);
        // More fields as needed
        lines.push(`      },`);
      }
    }
    lines.push(`    },`);

    // Specs
    if (specs) {
      lines.push(`    specs: {`);
      for (const [k, v] of Object.entries(specs)) {
        if (k !== 'id' && k !== 'product_id' && v) {
          lines.push(`      ${k}: '${String(v).replace(/'/g, "\\'")}',`);
        }
      }
      lines.push(`    },`);
    }

    lines.push(`    isPublished: ${p.is_published},`);
    lines.push(`    sortOrder: ${p.sort_order},`);
    lines.push(`  },`);
  }

  lines.push('];');
  lines.push('');
  lines.push('export function getProductById(id) { return rawProducts.find(p => p.id === id); }');
  lines.push('export function getProductsByCategory(cat) { return rawProducts.filter(p => p.category === cat); }');
  lines.push('export function getRelatedProducts(id) { const p = getProductById(id); if (!p?.relatedIds) return []; return p.relatedIds.map(id => getProductById(id)).filter(Boolean); }');
  lines.push('export { rawProducts };');
  lines.push('export default rawProducts;');

  return lines.join('\n');
}

export async function generateNewsMarkdown(opts: CodegenOptions): Promise<Map<string, string>> {
  const supabase = createClient(opts.supabaseUrl, opts.supabaseKey);
  const { data: articles } = await supabase
    .from('news_articles')
    .select('*')
    .eq('is_published', true);

  const files = new Map<string, string>();
  if (!articles) return files;

  for (const article of articles) {
    const frontmatter = [
      '---',
      `title: "${article.title}"`,
      `description: "${article.description || ''}"`,
      `date: "${article.date || ''}"`,
      `keywords: ${JSON.stringify(article.keywords || [])}`,
      `locale: "${article.locale}"`,
      article.hero_image_url ? `heroImage: "${article.hero_image_url}"` : '',
      '---',
      '',
      article.body_markdown,
    ].filter(Boolean).join('\n');

    const path = `content/news/${article.locale}/${article.slug}.md`;
    files.set(path, frontmatter);
  }

  return files;
}
