// CMS Codegen: Fetches published content from Supabase and generates JS/MD files
// Run by GitHub Actions before Vite build.
// Usage: node codegen.mjs

import { createClient } from '@supabase/supabase-js';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(SCRIPT_DIR, '../..');
const WEB_ROOT = join(PROJECT_ROOT, 'apps/web');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const OUTPUT_DIR = join(WEB_ROOT, 'src');

const CMS_CATEGORY_MAP = {
  waterproof_bt: 'Waterproof Bluetooth Speaker',
  normal_bt: 'Normal Bluetooth Speaker',
  specialty: 'Specialty Speaker',
  earbuds: 'Bluetooth Earbuds',
};

async function generateProducts() {
  console.log('[codegen] Generating products...');
  const { data: products, error } = await supabase
    .from('products')
    .select('*, product_translations(*), product_specs(*), product_images(media_id, sort_order, is_primary, media(*))')
    .eq('is_published', true)
    .order('sort_order');

  if (error) { console.error('Failed to fetch products:', error.message); return; }
  if (!products || products.length === 0) { console.log('[codegen] No published products found'); return; }

  const lines = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    `// Generated: ${new Date().toISOString()}`,
    '// Total published products: ' + products.length,
    '',
    'const cmsProducts = [',
  ];

  for (const p of products) {
    const images = (p.product_images || []).sort((a, b) => a.sort_order - b.sort_order);
    const en = (p.product_translations || []).find((t) => t.locale === 'en');
    const specs = p.product_specs || {};

    // Build image objects: full {src, w, h, srcset} when variants are processed, else plain URLs
    const imgObjects = images.map((img) => {
      const v = img.media?.variants || {};
      if (v.processed && v.variants) {
        const variantEntries = Object.entries(v.variants);
        const srcset = variantEntries
          .sort((a, b) => a[1].width - b[1].width)
          .map(([, d]) => `${d.url} ${d.width}w`)
          .join(', ');
        return {
          src: v.publicUrl,
          w: v.originalWidth || 1600,
          h: v.originalHeight || 1600,
          srcset,
        };
      }
      // Fallback: plain URL string
      return v.publicUrl || '';
    }).filter(img => img !== '');

    lines.push(`  {`);
    lines.push(`    slug: '${p.slug}',`);
    lines.push(`    name: '${(en?.name || '').replace(/'/g, "\\'")}',`);
    lines.push(`    category: '${CMS_CATEGORY_MAP[p.category] || p.category}',`);
    lines.push(`    image: ${JSON.stringify(imgObjects)},`);
    lines.push(`    features: ${JSON.stringify(en?.features || [])},`);
    lines.push(`    benefits: ${JSON.stringify(en?.benefits || [])},`);

    // Specs (flattened from product_specs table)
    const specEntries = Object.entries(specs).filter(([k, v]) => k !== 'id' && k !== 'product_id' && v);
    if (specEntries.length > 0) {
      lines.push(`    specs: {`);
      for (const [k, v] of specEntries) {
        lines.push(`      ${k}: '${String(v).replace(/'/g, "\\'")}',`);
      }
      lines.push(`    },`);
    }

    lines.push(`    downloads: ${JSON.stringify(p.downloads || [])},`);
    lines.push(`    sortOrder: ${p.sort_order || 0},`);
    lines.push(`  },`);
  }

  lines.push('];');
  lines.push('');
  lines.push('export { cmsProducts };');

  const outPath = join(OUTPUT_DIR, 'features/products/data/products.generated.js');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log(`[codegen] Wrote ${products.length} products to products.generated.js`);
}

async function generateNews() {
  console.log('[codegen] Generating news...');
  const { data: articles, error } = await supabase
    .from('news_articles')
    .select('*')
    .eq('is_published', true);

  if (error) { console.error('Failed to fetch news:', error.message); return; }
  if (!articles) return;

  for (const a of articles) {
    const frontmatter = [
      '---',
      `title: "${(a.title || '').replace(/"/g, '\\"')}"`,
      `description: "${(a.description || '').replace(/"/g, '\\"')}"`,
      `date: "${a.date || ''}"`,
      `keywords: ${JSON.stringify(a.keywords || [])}`,
      `locale: "${a.locale}"`,
      a.hero_image_url ? `heroImage: "${a.hero_image_url}"` : '',
      '---',
      '',
      a.body_markdown || '',
    ].filter(Boolean).join('\n');

    const outPath = join(WEB_ROOT, 'content/news', a.locale, `${a.slug}.md`);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, frontmatter);
  }
  console.log(`[codegen] Wrote ${articles.length} news articles`);
}

async function generateFaq() {
  console.log('[codegen] Generating FAQ...');
  const { data: sections, error } = await supabase
    .from('faq_sections')
    .select('*')
    .eq('is_published', true)
    .order('sort_order');

  if (error) { console.error('Failed to fetch FAQ:', error.message); return; }
  if (!sections || sections.length === 0) { console.log('[codegen] No published FAQ sections found'); return; }

  const overrides = {};
  for (const s of sections) {
    if (!overrides[s.locale]) overrides[s.locale] = {};
    overrides[s.locale][s.section_key] = {
      title: s.title,
      shortTitle: s.short_title,
      items: s.items,
    };
  }

  const lines = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    `// Generated: ${new Date().toISOString()}`,
    '',
    `const cmsFaqOverrides = ${JSON.stringify(overrides, null, 2)};`,
    '',
    'export { cmsFaqOverrides };',
  ];

  const outPath = join(OUTPUT_DIR, 'features/faq/data/faq.generated.js');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log(`[codegen] Wrote ${sections.length} FAQ sections to faq.generated.js`);
}

async function generateLegal() {
  console.log('[codegen] Generating legal pages...');
  const { data: pages, error } = await supabase
    .from('legal_page_translations')
    .select('*');

  if (error) { console.error('Failed to fetch legal:', error.message); return; }
  if (!pages || pages.length === 0) { console.log('[codegen] No legal page translations found'); return; }

  const overrides = {};
  for (const p of pages) {
    if (!overrides[p.page_type]) overrides[p.page_type] = {};
    overrides[p.page_type][p.locale] = {
      title: p.title,
      description: p.description,
      eyebrow: p.eyebrow,
      h1: p.h1,
      lead: p.lead,
      intro: p.intro,
      sections: p.sections,
    };
  }

  const lines = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    `// Generated: ${new Date().toISOString()}`,
    '',
    `const cmsLegalOverrides = ${JSON.stringify(overrides, null, 2)};`,
    '',
    'export { cmsLegalOverrides };',
  ];

  const outPath = join(OUTPUT_DIR, 'features/legal/data/legal.generated.js');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log(`[codegen] Wrote ${pages.length} legal page translations to legal.generated.js`);
}

async function generateSeoKeywords() {
  console.log('[codegen] Generating SEO keywords...');
  const { data: setting, error } = await supabase
    .from('site_settings')
    .select('*')
    .eq('key', 'seo_defaults')
    .single();

  if (error) { console.log('[codegen] No SEO settings found (using empty keywords)'); }

  const seoData = setting?.value || {};
  const coreKeywords = seoData.coreKeywords || [];
  const secondaryKeywords = seoData.secondaryKeywords || [];

  const lines = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    `// Generated: ${new Date().toISOString()}`,
    '',
    `const cmsCoreKeywords = ${JSON.stringify(coreKeywords)};`,
    `const cmsSecondaryKeywords = ${JSON.stringify(secondaryKeywords)};`,
    '',
    'export { cmsCoreKeywords, cmsSecondaryKeywords };',
  ];

  const outPath = join(OUTPUT_DIR, 'shared/seo/seoKeywords.generated.js');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log('[codegen] Wrote SEO keywords to seoKeywords.generated.js');
}

async function generateI18n() {
  console.log('[codegen] Generating i18n strings...');
  // Fetch site settings that contain translatable content
  const { data: siteSettings, error } = await supabase
    .from('site_settings')
    .select('*');

  if (error) { console.error('Failed to fetch site settings:', error.message); return; }

  // Build CMS messages from site settings like site_name, contact_info, social_links
  const cmsMessages = { en: {}, fr: {}, vi: {} };

  for (const s of (siteSettings || [])) {
    const val = typeof s.value === 'string' ? s.value : s.value;
    if (s.key === 'site_name') {
      for (const loc of ['en', 'fr', 'vi']) {
        cmsMessages[loc].siteName = val;
      }
    }
    if (s.key === 'contact_info') {
      const contact = typeof val === 'object' ? val : {};
      for (const loc of ['en', 'fr', 'vi']) {
        cmsMessages[loc].contactInfo = contact;
      }
    }
  }

  const lines = [
    '// Auto-generated by CMS codegen. DO NOT EDIT MANUALLY.',
    `// Generated: ${new Date().toISOString()}`,
    '',
    `const cmsMessages = ${JSON.stringify(cmsMessages, null, 2)};`,
    '',
    'export { cmsMessages };',
  ];

  const outPath = join(OUTPUT_DIR, 'shared/lib/i18n.generated.js');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log('[codegen] Wrote i18n strings to i18n.generated.js');
}

async function main() {
  console.log('[codegen] Starting content generation...');
  await generateProducts();
  await generateNews();
  await generateFaq();
  await generateLegal();
  await generateSeoKeywords();
  await generateI18n();
  console.log('[codegen] Done.');
}

main().catch((err) => {
  console.error('[codegen] Fatal error:', err);
  process.exit(1);
});
